language: php
php:
  - '7.0'

env:
  matrix:
    - COMPOSER_OPTIONS="--prefer-lowest --prefer-stable"
    - COMPOSER_OPTIONS=""

install:
  - composer update $COMPOSER_OPTIONS

script:
  - composer ci
